(define (write-bytes-seq port bytes)
  (for-each
   (lambda (b)
     (write-byte (if (char? b)
                     (char->integer b)
                     b)
                 port))
   bytes))

(define (write-elf-file filename)
  (let [(file (open-output-file filename))]
    (write-bytes-seq file '(#x7F #\E #\L #\F))
    (write-bytes-seq file '(#x1 #x1 #x1))
    (close-output-port file)))

(define elf-insn-types
  '(( none      .  0)
    ( M32       .  1)
    ( Sparc     .  2)
    ( i386      .  3)
    ( m68k      .  4)
    ( m88k      .  5)
    ( imcu      .  6)
    ( i860      .  7)
    ( mips1     .  8)
    ( mipsr3kle . 10)
    ( ppc       . 20)
    ( ppc64     . 21)
    ( arm       . 40)
    ( arm32     . 40)
    ( amd64     . 62)
    ( avr       . 83)
    ( openrisc  . 92)
    ( sharc     . 133)
    ( arm64     . 183)
    ( aarch64   . 183)
    ( avr32     . 185)
    ( cuda      . 190)
    ( z80       . 220)
    ( riscv     . 243)))
