(define xx (make-tokenizer))
(tokenizer-add-input xx "(display \"hello world\")")
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(tokenizer-tokenize xx)
(display "Output:")
(newline)
(display (map token-type (tokenizer-outqueue xx)))
(newline)
(display (map token-value (tokenizer-outqueue xx)))
(newline)
